# Importtant Libraries to use in Machine Learning

1. Numpy
2. Pandas
3. Matplotlib
4. Seaborn

### Numpy

- faster operations
- Allows several Mathematical Operations

In [1]:
import numpy as np

In [2]:
from time import process_time

py_list = [i for i in range(1000000)]
np_array = np.array([i for i in range(1000000)])

start_time = process_time()

# py_list = [i+5 for i in py_list]
np_array += 5

end_time = process_time()

print(end_time-start_time)

0.0007922760000003137


In [3]:
a = np.array([
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
], dtype=float)

a.shape

(3, 3)

In [4]:
# create a new np array initialized with zeroes
z = np.zeros((4, 4))

print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# create array with ones
ones = np.ones((3, 3), dtype=int)

print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
# create array with specific value

fives = np.full((4, 4), 5)

print(fives)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [7]:
# create an identity matrix
I4 = np.eye(4)

print(I4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# create a array with random values
rand = np.random.random((3, 4))

print(rand)

[[0.66357987 0.15592004 0.10903059 0.31821841]
 [0.20701794 0.01055637 0.93763971 0.63082164]
 [0.26446707 0.09884906 0.18665998 0.15464772]]


In [9]:
# create an array of integers with in a speific range
rand_int = np.random.randint(10, 20, (3, 2))

print(rand_int)

[[14 13]
 [19 17]
 [17 15]]


In [10]:
# array of evenly spaced values
d = np.linspace(10, 20, 6)

print(d)

[10. 12. 14. 16. 18. 20.]


In [11]:
np.add(a, ones)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

## Pandas

- Data Manipulation
- Data Analysis
- Data Cleaning

In [12]:
import pandas as pd

In [14]:
df = pd.read_csv("data/train_X.csv", header=None)

df

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

     777  778  779  780  781  782  783  
0      0    0    0    0    0    0    0  
1      0    0    0    0    0    0    0  
2      0    0    0    0    0    0    0  
3      0    0    0    0    0    0    0  
4      0    0    0    0    0    0    0  
..   ...  ...  ...  ...  ...  ...  ...  
995    0    0    0    0    0    0    0  
996    0    0    0    0    0    0    0  
997    0    0    0    0    0    0    0  
998    0    0    0    0    0    0    0  
999    0    0    0    0    0    0    0  

[1000 rows x 784 columns]

In [15]:
df.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 784 columns]